name: mobile
description: AI-EHR Flutter Mobile App
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  
  # Navigation
  go_router: ^14.2.3
  
  # State Management
  provider: ^6.1.2
  
  # HTTP Client (for future API integration)
  http: ^1.2.2
  
  # Date/Time utilities
  intl: ^0.19.0
  
  # Cards and animations
  flutter_staggered_animations: ^1.1.1
  
  # Charts for health data
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Enable custom fonts and assets
  assets:
    - assets/images/
    - assets/icons/
  
  # Custom fonts (optional)
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
